### ISSUE TITLE
UnboundLocalError: local variable 'cpu_pcts' referenced before assignment

### ISSUE THREAD

**Issue by mrPsycho** [kxr/check_linux_metrics#2]
Hello,

i know that script is very old.
but:
<pre>
[root@D01mplaceAFE01 ~]# ./check_linux_metrics.py cpu
Traceback (most recent call last):
  File "./check_linux_metrics.py", line 753, in <module>
    check_cpu()
  File "./check_linux_metrics.py", line 84, in check_cpu
    cpu_pcts['steal'] = 0
UnboundLocalError: local variable 'cpu_pcts' referenced before assignment
</pre>

**Comment by Aleksey-Maksimov** [comment]
+1

**Comment by Aleksey-Maksimov** [comment]
Some problem
 
Traceback (most recent call last):
File "/usr/lib/nagios/plugins/check_linux_metrics.py", line 757, in <module>
    check_cpu( warn=sys.argv[2], crit=sys.argv[3] )
  File "/usr/lib/nagios/plugins/check_linux_metrics.py", line 84, in check_cpu
    cpu_pcts['steal'] = 0
UnboundLocalError: local variable 'cpu_pcts' referenced before assignment

**Comment by alternaivan** [comment]
Hello, 

I had the same error. I fixed the issue by deleting the following file _proc_stat_ and run the script again.
The file was located in /var/tmp/linux_metrics/ and it is defined as INTERIM_DIR variable in line number 33 in the check_linux_metrics.py script.

Regards!
